# Secured db and connection will be in a different brnch
version: "3.9"
services:
  mongodb:
    container_name: mongodb-todo
    image: mongo:8.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
       - mongodb-data:/data/db
  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/todolist
      
volumes:
  mongodb-data:
    driver: local
  mongo-config:
    driver: local  