# Secured db and connection will be in a different brnch
services:
  mongo:
    image: mongo:8.0 
    container_name: mongodb-todo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local